### ISSUE TITLE
Ubuntu 20 dd成debian 10报错

### ISSUE THREAD

**Issue by cncherisher** [MeowLove/Network-Reinstall-System-Modify#24]
```bash
# Install

Auto Mode insatll [Debian] [buster] [amd64]. 

[Debian] [buster] [amd64] Downloading...
Error, Not found interfaces config.
---------------------------------------------------------------------------------------------------------------------
 启动 安装 
 Start Installation 
---------------------------------------------------------------------------------------------------------------------


---------------------------------------------------------------------------------------------------------------------
 启动 安装 
 Start Installation 

root@ubuntu:~# 
```
网络配置在/etc/netplan/01-netcfg.yaml内
```
#This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    ens3:
      addresses: [ aaa.bbb.ccc.196/24 ]
      gateway4: aaa.bbb.ccc.254
      nameservers:
          addresses:
              - "1.1.1.1"
```
